/**
 * Données initiales des questions du test de recrutement (source du seed).
 * Contenu fidèle au PDF officiel « Test Psychotechnique — Jeune Talent 2026 ».
 *
 * ⚠️ NE PAS importer côté client : contient les bonnes réponses (`c`).
 * Utilisé uniquement par le seed (lib/db/seed.ts). La source de vérité en
 * production est la table `recruitment_questions` (éditable via le dashboard).
 */
import type { Domain } from "./recruitment";

export interface SeedQuestion {
  block: number;
  domain: Domain | null;
  section: string;
  text: string;
  options: string[];
  correctIndex: number;
  explanation: string;
}

type RawQ = { s: string; t: string; o: string[]; c: number; e: string };

/* ─── Bloc 1 — Raisonnement logique (commun) ─────────────────────────── */
const B1: RawQ[] = [
  { s: "Raisonnement logique", t: "Une suite suit la règle : chaque terme est la somme des deux précédents moins 1. Si les deux premiers termes sont 3 et 5, quel est le 5e terme ?", o: ["19", "20", "21", "22"], c: 2, e: "T3=3+5-1=7 · T4=5+7-1=11 · T5=7+11-1=17. Piège : beaucoup calculent T5=7+12=19 en oubliant le -1." },
  { s: "Raisonnement logique", t: "Si tous les managers sont des leaders, et que certains leaders sont des créatifs, alors :", o: ["Tous les managers sont créatifs", "Certains managers peuvent être créatifs", "Aucun manager n'est créatif", "Tous les créatifs sont managers"], c: 1, e: "Syllogisme partiel : managers ⊂ leaders, certains leaders ∩ créatifs. On ne peut affirmer que certains managers peuvent être créatifs." },
  { s: "Raisonnement logique", t: "Un robinet remplit un réservoir en 6 heures. Une fuite le vide en 9 heures. En combien de temps le réservoir sera-t-il plein s'il est vide au départ ?", o: ["15h", "18h", "12h", "24h"], c: 1, e: "Débit net = 1/6 - 1/9 = 1/18 par heure → 18h. Piège : additionner 6+9=15." },
  { s: "Raisonnement logique", t: "Dans une salle, 60% des personnes parlent français, 40% parlent anglais, et 25% parlent les deux. Quel pourcentage ne parle aucune des deux langues ?", o: ["0%", "25%", "15%", "5%"], c: 1, e: "P(F∪A) = 60+40-25 = 75%. Donc 25% ne parlent aucune des deux. Piège : oublier de soustraire l'intersection." },
  { s: "Raisonnement logique", t: "Un homme regarde un portrait et dit : 'Je n'ai ni frère ni sœur, mais le père de cet homme est le fils de mon père.' De qui regarde-t-il le portrait ?", o: ["Son oncle", "Son cousin", "Son fils", "Lui-même"], c: 2, e: "Le père du portrait est le fils de son père, donc lui-même. Il regarde le portrait de son fils." },
  { s: "Raisonnement logique", t: "Une entreprise augmente ses prix de 20%, puis les réduit de 20%. Quel est le prix final par rapport au prix initial ?", o: ["Identique", "4% de moins", "4% de plus", "20% de moins"], c: 1, e: "1,20 × 0,80 = 0,96. Piège classique : +20% puis -20% ne s'annulent pas (base plus haute)." },
  { s: "Raisonnement logique", t: "Quel nombre complète logiquement : 2, 6, 12, 20, 30, ?", o: ["40", "42", "44", "48"], c: 1, e: "Écarts : +4, +6, +8, +10, +12 → 30+12=42. Les écarts augmentent de 2." },
  { s: "Raisonnement logique", t: "Koffi est plus grand que Ama. Ama est plus petite que Brice. Brice est plus petit que Koffi. Qui est le plus petit ?", o: ["Koffi", "Ama", "Brice", "Impossible à déterminer"], c: 1, e: "Koffi > Brice > Ama. Ama est donc la plus petite." },
  { s: "Raisonnement logique", t: "Sur 100 candidats, 70 ont réussi l'écrit, 60 ont réussi l'oral. Si 20 ont échoué aux deux épreuves, combien ont réussi les deux ?", o: ["30", "40", "50", "60"], c: 2, e: "Réussi au moins une = 100-20 = 80. 80 = 70+60-P(E∩O) → P(E∩O)=50." },
  { s: "Raisonnement logique", t: "Un code remplace chaque lettre par celle qui la suit de 2 positions dans l'alphabet (Z→B, Y→A). Quel est le code de 'IZICHANGE' ?", o: ["KBKEJCPIG", "KBKEJCPIG", "KBKEJCPIG", "LCLEKDQJH"], c: 0, e: "I→K, Z→B, I→K, C→E, H→J, A→C, N→P, G→I, E→G → KBKEJCPIG. Options A/B/C identiques pour tester la concentration — D est délibérément faux." },
];

/* ─── Bloc 2 — Personnalité & comportement (commun) ──────────────────── */
const B2: RawQ[] = [
  { s: "Autonomie & prise de décision", t: "Votre manager est absent et une décision urgente doit être prise sur un projet dont vous êtes responsable. Vous :", o: ["Attendez son retour pour ne pas dépasser votre périmètre.", "Prenez la décision la plus raisonnée, documentez votre raisonnement et informez votre manager dès son retour.", "Consultez tous vos collègues disponibles pour avoir un consensus avant d'agir.", "Repoussez la décision en invoquant l'absence de votre manager."], c: 1, e: "Agit dans son périmètre, raisonne sous pression, rend compte. A = manque d'initiative · C = perte de temps · D = évitement." },
  { s: "Autonomie & prise de décision", t: "Vous réalisez qu'une tâche confiée à un collègue ne sera pas terminée à temps et met en danger une deadline client. Vous :", o: ["Informez votre manager et attendez ses instructions.", "Reprenez la tâche vous-même sans en parler pour ne pas embarrasser votre collègue.", "Discutez immédiatement avec votre collègue, proposez un coup de main et alertez le manager si la deadline reste compromise.", "Informez le client directement que la deadline sera dépassée."], c: 2, e: "Collaboration + communication ascendante + responsabilité partagée. A = passivité · B = micro-management · D = escalade prématurée." },
  { s: "Rigueur & gestion de l'erreur", t: "Après avoir soumis un rapport important, vous découvrez une erreur de calcul significative déjà lue par plusieurs personnes. Vous :", o: ["Corrigez le document en silence.", "Attendez que quelqu'un signale l'erreur.", "Informez immédiatement les personnes concernées, fournissez la version corrigée et expliquez l'origine de l'erreur.", "Signalez l'erreur uniquement à votre manager."], c: 2, e: "Transparence proactive = valeur centrale en fintech. C allie responsabilité et résolution active. D insuffisant." },
  { s: "Rigueur & gestion de l'erreur", t: "On vous confie simultanément trois tâches avec des deadlines proches. Que faites-vous en premier ?", o: ["Commencez par la tâche la plus courte pour en finir au moins une rapidement.", "Demandez à votre manager de choisir.", "Évaluez l'impact business de chacune, priorisez et communiquez vos arbitrages au manager.", "Travaillez sur les trois en parallèle."], c: 2, e: "Priorisation par impact business = profil senior. A = court terme · B = abdication · D = dispersion." },
  { s: "Travail en équipe & communication", t: "En réunion, vous êtes convaincu(e) que la solution de votre manager est sous-optimale. Vous :", o: ["Ne dites rien — votre manager a l'autorité.", "Exprimez calmement une alternative avec des arguments factuels.", "Attendez la fin de la réunion pour en parler en privé.", "Parlez-en à vos collègues après la réunion."], c: 1, e: "Courage + argumentation factuelle dans le bon cadre. A = conformisme · C = trop prudent · D = contre-productif." },
  { s: "Travail en équipe & communication", t: "Un collègue au style très différent génère des frictions. Votre approche :", o: ["Signalez au manager pour qu'il arbitre.", "Adaptez entièrement votre style au sien.", "Proposez un échange structuré pour identifier les frictions et construire une façon de travailler ensemble.", "Minimisez vos interactions."], c: 2, e: "Résolution directe et collaborative. C = maturité · A = escalade · B = perte d'identité · D = évitement." },
  { s: "Résistance au stress & adaptabilité", t: "À J-2 de la livraison, les spécifications changent significativement. Votre première réaction :", o: ["Une frustration que vous exprimez clairement.", "Réévaluer immédiatement l'impact et proposer un plan révisé.", "Accepter les changements sans commenter.", "Demander un report de deadline."], c: 1, e: "Analytique puis proactif. B = résilience structurée · A = émotionnel · C = passivité · D = défensif." },
  { s: "Résistance au stress & adaptabilité", t: "Plusieurs collègues vous sollicitent en pleine tâche complexe. Vous :", o: ["Mettez votre tâche en pause et gérez dans l'ordre.", "Ignorez jusqu'à terminer.", "Évaluez l'urgence de chaque demande, traitez l'urgente, fixez un délai pour les autres.", "Demandez à tous de mettre leur demande par écrit."], c: 2, e: "Priorisation rapide + communication claire. C = intelligence situationnelle · A = dispersion · B = isolement." },
  { s: "Résultats & initiative", t: "Mission avec objectif clair mais sans méthode imposée. Votre approche naturelle :", o: ["Demandez au manager comment il procéderait.", "Reproduisez ce que vous avez vu faire dans une situation similaire.", "Proposez votre propre méthode, validez rapidement avec le manager, exécutez en ajustant.", "Cherchez la meilleure pratique sur internet avant de commencer."], c: 2, e: "Autonomie + validation rapide + itération. C = efficience · A = dépendance · B = copie · D = perte de temps." },
  { s: "Résultats & initiative", t: "Fin de journée, tout accompli. Il vous reste 30 minutes. Vous :", o: ["Partez à l'heure — vous avez fait ce qui était demandé.", "Prenez de l'avance sur la tâche de demain la plus critique.", "Naviguez sur internet — une bonne pause méritée.", "Cherchez ce que vous auriez pu faire mieux."], c: 1, e: "Haute performance = anticipe. B = valeur ajoutée. D = réflexivité, bon second choix. A, C = exécutant." },
  { s: "Éthique & intégrité", t: "Un collègue contourne une procédure interne pour gagner du temps sans conséquence visible. Vous :", o: ["N'intervenez pas — cela ne vous regarde pas.", "En parlez à d'autres collègues avant de décider.", "Signalez au manager ou au RH, de façon factuelle.", "En parlez directement à votre collègue pour comprendre et l'encourager à respecter la procédure."], c: 3, e: "D = préserve la relation + chance de correction. C acceptable si D échoue. A, B = évitement." },
  { s: "Éthique & intégrité", t: "En entretien, on vous demande vos points faibles. Vous :", o: ["'Je suis perfectionniste et j'ai du mal à déléguer' — une faiblesse qui ressemble à une qualité.", "Citez un vrai point de développement, expliquez comment vous le travaillez et donnez un exemple concret de progrès.", "Dites n'avoir pas de faiblesse majeure dans les domaines importants.", "Reformulez en parlant d'un domaine à approfondir."], c: 1, e: "Authenticité + conscience de soi + posture de développement. A, C, D = réponses formatées détectées." },
];

/* ─── Bloc 3A — Opérations ───────────────────────────────────────────── */
const OPS: RawQ[] = [
  { s: "Aptitudes Opérations", t: "Un client affirme avoir envoyé un virement de 50 000 FCFA mais le destinataire dit ne pas l'avoir reçu. Votre première action :", o: ["Lui demander de patienter 24h car les virements prennent du temps.", "Lui demander son numéro de transaction et consulter le statut en temps réel dans le système.", "Lui expliquer que la responsabilité peut venir du côté destinataire.", "L'escalader immédiatement au service technique sans lui parler."], c: 1, e: "Collecter l'info précise (N° de transaction) et vérifier le statut avant tout. A = vague · C = préjugé · D = escalade sans diagnostic." },
  { s: "Aptitudes Opérations", t: "Un client étranger vous contacte en anglais. Votre niveau d'anglais est fonctionnel mais limité. Vous :", o: ["Lui répondez en français en espérant qu'il comprenne.", "Utilisez un outil de traduction pour comprendre sa demande et formulez une réponse simple et claire en anglais.", "Transférez immédiatement à un collègue anglophone sans explication au client.", "Lui demandez d'écrire en français car c'est la langue officielle de l'entreprise."], c: 1, e: "Effort dans la langue du client = professionnalisme. C acceptable avec explication. A, D = mauvais service." },
  { s: "Aptitudes Opérations", t: "Vous traitez 15 tickets. Un nouveau arrive marqué 'URGENT' par le client. Vous :", o: ["Le traitez immédiatement car le client a marqué URGENT.", "Évaluez le contenu réel du ticket avant de décider de sa priorité.", "L'ajoutez en fin de file — chaque client pense que son problème est urgent.", "L'escaladez au manager car vous êtes déjà surchargé(e)."], c: 1, e: "L'urgence déclarée ≠ urgence réelle. A = réactivité aveugle · C = négligence · D = escalade trop rapide." },
  { s: "Aptitudes Opérations", t: "Problème résolu, mais l'historique montre 3 incidents similaires en 2 mois. Vous :", o: ["Clôturez le ticket — votre rôle est de résoudre le problème actuel.", "Signalez l'anomalie au manager ou à l'équipe technique avec un résumé des 3 incidents.", "Demandez au client pourquoi il rencontre toujours ce problème.", "Proposez au client de changer de produit ou de service."], c: 1, e: "Détecter les patterns et les remonter. A = vision courte · C = charge sur le client · D = dépassement de rôle." },
  { s: "Aptitudes Opérations", t: "Un client menace de saisir l'APDP suite à une vérification d'identité. Vous :", o: ["Abandonnez la procédure pour l'apaiser.", "Expliquez calmement que c'est une obligation légale, citez le cadre applicable et confirmez ses droits.", "Transférez immédiatement le dossier au département juridique.", "Lui demandez de formuler sa plainte par écrit."], c: 1, e: "Connaissance du cadre = assurance sans capitulation. A = manque de rigueur · C = escalade inutile · D = fuite." },
  { s: "Aptitudes Opérations", t: "Un client demande pourquoi son système a bloqué sa transaction. Vous ne connaissez pas la raison exacte. Vous :", o: ["Inventez une explication technique plausible.", "Dites honnêtement que vous n'avez pas l'information, vérifiez avec l'équipe et rappellerez dans un délai précis.", "Dites que le système est automatique et que vous n'avez pas accès à ces informations.", "Suggérez de réessayer plus tard."], c: 1, e: "Transparence + engagement de rappel avec délai précis. A = mensonge · C = sans engagement · D = désinvolture." },
  { s: "Aptitudes Opérations", t: "Changement tarifaire public dans 3 jours. Un client vous interroge. Vous :", o: ["Lui donnez l'information — il le saura dans 3 jours.", "Confirmez qu'il n'y a aucun changement prévu.", "Indiquez ne pas pouvoir commenter des informations non officielles et invitez à suivre les communications officielles.", "Refusez de répondre sans explication."], c: 2, e: "Infos internes non publiées = confidentielles. A = faute · B = mensonge · D = impolitesse." },
  { s: "Aptitudes Opérations", t: "En plein rush, le système tombe en panne 20 minutes. Des clients s'impatientent. Vous :", o: ["Attendez silencieusement que le système revienne.", "Informez proactivement les clients de la panne, estimez un délai, proposez un rappel ou une alternative.", "Demandez à tous les clients de rappeler plus tard.", "Escaladez au manager et attendez ses instructions avant toute communication."], c: 1, e: "Communication proactive = service client mature. A, D = passivité · C = rejet du client." },
  { s: "Aptitudes Opérations", t: "Un process interne inefficace crée de la friction avec les clients. Vous :", o: ["Continuez à le suivre — ce n'est pas votre rôle de changer les process.", "En parlez à un collègue de confiance pour valider votre ressenti.", "Documentez le problème avec des exemples concrets et le proposez au manager comme point d'amélioration.", "Adaptez le process à votre façon sans en parler à personne."], c: 2, e: "Amélioration continue = remontée structurée. A = conformisme inerte · D = non-conformité risquée." },
  { s: "Aptitudes Opérations", t: "Un collègue vous demande de prendre un de ses tickets. Vous êtes proche de votre limite. Vous :", o: ["Acceptez sans condition — la solidarité d'équipe est prioritaire.", "Refusez poliment car vous êtes surchargé(e).", "Évaluez votre capacité réelle, exprimez ce que vous pouvez faire et alertez si la charge dépasse les ressources.", "Acceptez le ticket mais réduisez la qualité de votre travail."], c: 2, e: "Évaluation honnête + transparence + remontée systémique. A = surengagement · B = manque de solidarité · D = sacrifice qualité." },
];

/* ─── Bloc 3B1 — Graphiste-Monteur vidéo ─────────────────────────────── */
const GRAPHISTE: RawQ[] = [
  { s: "Aptitudes Graphiste", t: "Un client interne vous soumet un brief très vague : 'Quelque chose de moderne et percutant pour notre nouvelle fonctionnalité.' Votre première action est de :", o: ["Créer plusieurs propositions variées et lui soumettre pour choisir.", "Demander un brief détaillé : cible, message clé, ton, format, contraintes de la charte graphique.", "Reproduire le style du dernier visuel validé par ce client.", "Proposer directement votre interprétation créative sans poser de questions."], c: 1, e: "Un bon designer ne part jamais sans brief complet. B protège le créatif ET le client. A = perte de temps · C = créativité nulle · D = hors-sujet." },
  { s: "Aptitudes Graphiste", t: "Vous livrez un visuel validé lors du brief mais le responsable marketing demande à la dernière minute de 'tout refaire dans un autre style'. Vous :", o: ["Acceptez sans commenter et recommencez depuis zéro.", "Refusez catégoriquement — le brief était validé.", "Expliquez calmement que ce changement sort du scope initial, évaluez le temps supplémentaire requis et demandez une validation formelle avant de continuer.", "Faites les modifications mais en signalant en passant que le brief avait été validé."], c: 2, e: "Gestion de scope = compétence clé. C = posture juste et constructive. A = perte de valeur · B = rigidité · D = passivité." },
  { s: "Aptitudes Graphiste", t: "Vous devez créer un visuel pour Instagram et un autre pour LinkedIn pour la même campagne. Votre approche :", o: ["Créez un seul visuel et exportez-le aux deux formats.", "Adaptez le visuel à chaque plateforme : format carré/vertical pour Instagram, 1200x627px pour LinkedIn, messages et tons différents selon la cible.", "Créez le visuel LinkedIn en priorité car c'est le réseau le plus important.", "Demandez au responsable de choisir une seule plateforme pour ce budget."], c: 1, e: "Chaque plateforme a ses codes. Adapter n'est pas dupliquer. A = erreur de format · C = décision sans base · D = limitation arbitraire." },
  { s: "Aptitudes Graphiste", t: "Vous recevez un retour négatif sur un visuel : 'Ce n'est pas ce que je voulais.' Sans autres précisions. Vous :", o: ["Refaites le visuel selon votre propre interprétation du retour.", "Demandez des précisions spécifiques : qu'est-ce qui ne convient pas exactement ? Couleurs, composition, message, ton ?", "Présentez 3 nouvelles propositions très différentes pour couvrir toutes les possibilités.", "Renvoyez le brief initial pour montrer que vous avez respecté les instructions."], c: 1, e: "Un retour vague ne guide pas une correction. B garantit l'alignement. A, C = devine à l'aveugle · D = défensif." },
  { s: "Aptitudes Graphiste", t: "Votre logiciel de montage vidéo plante 2 heures avant la livraison d'une vidéo à publier. Le projet est partiellement sauvegardé. Vous :", o: ["Attendez que le logiciel redémarre et espérez récupérer le fichier.", "Alertez immédiatement le responsable de l'état du problème et du délai probable, activez un plan B (autre poste, autre logiciel, version antérieure) et continuez à travailler.", "Demandez un report de deadline au client sans en parler à votre manager.", "Livrez la version partielle disponible en expliquant le problème technique."], c: 1, e: "Gestion de crise = alerter + action parallèle. A = perd du temps · C = unilatéral · D = sous-qualité sans concertation." },
  { s: "Aptitudes Graphiste", t: "Le responsable marketing vous demande de créer un visuel 'dans le style d'une marque concurrente'. Vous :", o: ["Copiez le style fidèlement — c'est une demande interne, pas une publication.", "Créez le visuel demandé sans réserve.", "Expliquez que copier un style concurrent crée un risque juridique (droit d'auteur) et de confusion de marque, et proposez de vous en inspirer tout en restant dans la charte IZICHANGE.", "Refusez catégoriquement sans proposer d'alternative."], c: 2, e: "Connaissance juridique + proposition constructive. A, B = risque légal · D = blocage sans solution." },
  { s: "Aptitudes Graphiste", t: "Vous travaillez sur une vidéo de 90 secondes. Le montage final dure 2 min 30. Le chef de département demande de respecter le format 90 secondes. Vous :", o: ["Accélérez légèrement la vidéo pour réduire la durée.", "Identifiez les passages les moins essentiels avec le client, coupez ce qui peut l'être sans nuire au message, et proposez une version longue pour d'autres supports.", "Livrez la version 2 min 30 en argumentant que le contenu justifie la durée.", "Coupez brutalement à 90 secondes sans revoir la structure narrative."], c: 1, e: "Respect du format + concertation + réutilisation. A = qualité dégradée · C = non-respect du brief · D = coupure arbitraire." },
  { s: "Aptitudes Graphiste", t: "Un collègue non créatif modifie votre visuel sans vous consulter avant de le publier. Vous :", o: ["Ne dites rien pour éviter le conflit.", "Signalez le problème directement et calmement à votre collègue, expliquez pourquoi les modifications non validées nuisent à la cohérence de la charte et proposez un process de validation pour l'avenir.", "Allez directement voir le manager pour signaler la faute.", "Publiez une version corrigée sans en parler à personne."], c: 1, e: "Résolution directe + constructive + systémique. A = évitement · C = escalade trop rapide · D = unilatéral." },
  { s: "Aptitudes Graphiste", t: "Vous devez choisir entre deux polices pour un visuel IZICHANGE : une police tendance mais peu lisible sur mobile, et la police de la charte graphique. Vous :", o: ["Choisissez la police tendance — l'esthétique prime pour une fintech moderne.", "Respectez la charte graphique — la cohérence de marque n'est pas négociable, surtout en B2C.", "Proposez au responsable les deux options en expliquant avantages et inconvénients.", "Utilisez les deux polices dans le même visuel pour un rendu dynamique."], c: 1, e: "Charte graphique = cohérence de marque et lisibilité. A = amateur · C = décision du designer · D = incohérence." },
  { s: "Aptitudes Graphiste", t: "Vous venez de rejoindre IZICHANGE et vous estimez que la charte graphique actuelle est dépassée. Vous :", o: ["Proposez directement un nouveau logo et une nouvelle identité visuelle.", "Continuez avec la charte existante, documentez vos observations sur ses limites et proposez une réflexion structurée sur l'évolution de l'identité lors d'un point avec votre responsable.", "Appliquez subtilement vos propres préférences stylistiques sur vos créations.", "Ne dites rien — ce n'est pas votre rôle de remettre en question les choix antérieurs."], c: 1, e: "Respect du cadre + remontée structurée + initiative maîtrisée. A = dépassement · C = non-conformité · D = passivité." },
];

/* ─── Bloc 3B2 — CRM & Relation Client ───────────────────────────────── */
const CRM: RawQ[] = [
  { s: "Aptitudes CRM", t: "Vous devez segmenter une base de 5 000 contacts pour une campagne de réactivation des clients inactifs depuis 6 mois. Quel filtre appliquez-vous en priorité ?", o: ["Tous les contacts ayant un email valide.", "Les contacts dont la dernière transaction date de plus de 6 mois et qui ont eu au moins une transaction historique.", "Les contacts ayant ouvert au moins un email dans les 6 derniers mois.", "Les contacts dont le profil est complet (email + téléphone + nom)."], c: 1, e: "Réactivation = clients actifs mais dormants (>6 mois). B combine les deux critères. A, D = qualité données · C = contradictoire." },
  { s: "Aptitudes CRM", t: "Le taux d'ouverture de vos emails est de 18% contre 25% en moyenne sectorielle. Quelle est votre première hypothèse à tester ?", o: ["Le contenu des emails est mauvais.", "L'objet des emails n'est pas assez percutant ou pertinent.", "La liste d'envoi est trop grande.", "L'heure d'envoi n'est pas optimale."], c: 1, e: "L'objet est la première chose vue. Un mauvais objet explique un faible taux avant même la lecture." },
  { s: "Aptitudes CRM", t: "Un client VIP signale qu'il a reçu un email de promotion destiné aux nouveaux clients alors qu'il est client depuis 3 ans. Vous :", o: ["Vous excusez et expliquez que c'est une erreur de segmentation.", "Vous excusez sincèrement, expliquez l'erreur, proposez une compensation adaptée à son statut VIP et corrigez immédiatement sa segmentation dans le CRM.", "Expliquez que les promotions ne sont pas cumulables.", "Lui proposez de bénéficier quand même de la promotion des nouveaux clients."], c: 1, e: "Gestion VIP = reconnaissance + correction + compensation. A = incomplet · C = rigide · D = traite le VIP comme un nouveau." },
  { s: "Aptitudes CRM", t: "Vous constatez qu'un segment de clients à fort potentiel n'a eu aucune interaction depuis 4 mois. Votre recommandation est :", o: ["Lancer immédiatement une campagne email de réactivation sur ce segment.", "Analyser d'abord pourquoi : ont-ils reçu des emails ? Les ont-ils ouverts ? Ont-ils eu des problèmes avec le service ? Puis proposer une action ciblée.", "Transférer ce segment à l'équipe commerciale pour un suivi téléphonique.", "Attendre que ces clients reprennent contact d'eux-mêmes."], c: 1, e: "Diagnostic avant action = règle d'or du CRM. A = agit sans comprendre · C = escalade sans analyse · D = inertie." },
  { s: "Aptitudes CRM", t: "Votre manager vous demande de mesurer l'efficacité d'une campagne de fidélisation. Quel indicateur est le plus pertinent ?", o: ["Le nombre d'emails envoyés.", "Le taux d'ouverture des emails de la campagne.", "Le taux de rétention, l'évolution du panier moyen et le NPS des clients ciblés avant et après la campagne.", "Le nombre de nouveaux abonnés générés par la campagne."], c: 2, e: "Fidélisation = rétention + valeur + satisfaction. A, B = délivrance · D = acquisition." },
  { s: "Aptitudes CRM", t: "Un client écrit un email très agressif suite à un problème technique. Il insulte le service et menace de partir chez un concurrent. Vous :", o: ["Répondez point par point à ses arguments pour rétablir les faits.", "Prenez du recul, répondez avec calme et empathie en reconnaissant son inconfort, expliquez les mesures prises et proposez un suivi personnalisé.", "Transférez le cas à votre manager — ce client est trop difficile à gérer.", "Attendez que le client se calme avant de répondre."], c: 1, e: "Empathie + solution + suivi = gestion de crise relationnelle. A = confrontation · C = abandon · D = délai qui aggrave." },
  { s: "Aptitudes CRM", t: "Vous découvrez dans le CRM des données clients manifestement incorrectes (doublons, emails invalides, numéros erronés). Vous :", o: ["Laissez les données telles quelles — ce n'est pas votre rôle de nettoyer la base.", "Nettoyez discrètement les données sans en parler à personne.", "Documentez l'ampleur du problème, alertez votre responsable et proposez un plan de nettoyage et de prévention (règles de saisie, validation automatique).", "Supprimez toutes les données douteuses pour assainir la base."], c: 2, e: "Qualité des données = fondation du CRM. A = négligence · B = non coordonné · D = perte potentielle de données valides." },
  { s: "Aptitudes CRM", t: "On vous demande de rédiger un email de prospection B2B pour des PME locales. Quelle structure choisissez-vous ?", o: ["Présentation complète d'IZICHANGE, liste exhaustive des fonctionnalités, tarifs, contact.", "Accroche sur un problème concret des PME, promesse de solution, un seul bénéfice clé, un CTA simple.", "Un email long et détaillé pour montrer la crédibilité et le sérieux de l'entreprise.", "Un email avec uniquement le logo et un lien vers le site web."], c: 1, e: "Problème → solution → bénéfice → CTA. Court, ciblé. A, C = inside-out · D = aucun effort." },
  { s: "Aptitudes CRM", t: "Vous constatez qu'un même client a contacté le service client 5 fois ce mois pour des problèmes différents. Votre action :", o: ["Ne faites rien — c'est normal pour certains clients.", "Signalez le cas à l'équipe technique avec un résumé des 5 incidents pour investigation, et proposez un suivi personnalisé proactif à ce client.", "Contactez le client pour lui expliquer comment mieux utiliser le service.", "Classifiez ce client comme 'client difficile' dans le CRM."], c: 1, e: "5 contacts = signal systémique. B = détecte + remonte + fidélise. A = inertie · C = charge sur le client · D = stigmatisation." },
  { s: "Aptitudes CRM", t: "Votre rapport mensuel montre que le taux de conversion de vos landing pages est de 1,2% contre 3,5% en moyenne sectorielle. Votre hypothèse prioritaire :", o: ["Le budget publicitaire est insuffisant.", "La landing page elle-même — proposition de valeur, CTA, temps de chargement, adéquation message/audience.", "La qualité des visuels dans les publicités.", "Le choix des plateformes publicitaires."], c: 1, e: "Faible conversion après clic → la landing page. A, C = trafic entrant · D = distribution." },
];

/* ─── Bloc 3B3 — Social Media & Content ──────────────────────────────── */
const SOCIAL: RawQ[] = [
  { s: "Aptitudes Social Media", t: "Vous publiez un post Instagram pour IZICHANGE avec pour objectif d'acquérir de nouveaux utilisateurs 18-35 ans. Quelle accroche est la plus efficace ?", o: ["'IZICHANGE — la plateforme de paiement numérique fiable et sécurisée pour vos transactions.'", "'Vos virements. Votre rythme. 24h/24 sans frais cachés. Téléchargez maintenant.'", "'Nous sommes fiers d'annoncer que IZICHANGE est disponible sur toutes les plateformes.'", "'Pour en savoir plus sur nos services, visitez notre site web.'"], c: 1, e: "B = bénéfice client direct + CTA clair. A = jargon corporate · C = institutionnel · D = sans bénéfice ni CTA." },
  { s: "Aptitudes Social Media", t: "Un commentaire négatif public sur votre page Facebook : un client se plaint d'une transaction non reçue. Vous :", o: ["Supprimez le commentaire — il nuit à l'image.", "Répondez publiquement en reconnaissant sa frustration, vous excusez et invitez le client en message privé avec son numéro de transaction.", "Répondez publiquement avec tous les détails techniques de la transaction.", "Ignorez — un avis isolé n'impacte pas l'image globale."], c: 1, e: "Reconnaissance publique + invitation au privé = best practice. A = désastreux · C = violation de confidentialité · D = négligence." },
  { s: "Aptitudes Social Media", t: "Les statistiques montrent que les posts publiés le jeudi entre 18h et 20h ont 40% plus d'engagement. Que faites-vous ?", o: ["Publiez tous vos posts le jeudi entre 18h et 20h.", "Concentrez les posts à fort enjeu sur ce créneau, testez d'autres créneaux sur une période définie et ajustez selon les données.", "Ignorez cette statistique — le contenu compte plus que l'heure.", "Demandez la validation de votre manager avant d'ajuster quoi que ce soit."], c: 1, e: "Data-driven = tester, confirmer, optimiser. A = rigide · C = ignore la donnée · D = excès de prudence." },
  { s: "Aptitudes Social Media", t: "On vous demande de proposer une stratégie de contenu LinkedIn pour cibler les PME béninoises. Votre première étape est :", o: ["Créer immédiatement 10 posts variés pour montrer votre réactivité.", "Analyser d'abord les comportements de la cible sur LinkedIn (types de contenu, horaires, formats), puis définir les objectifs (notoriété, trafic, leads) avant de planifier.", "Reproduire la stratégie de la concurrence qui fonctionne bien.", "Publier quotidiennement pour maximiser la fréquence."], c: 1, e: "Stratégie avant exécution. A = sans cap · C = copie · D = quantité sans qualité." },
  { s: "Aptitudes Social Media", t: "Un collaborateur interne publie des informations confidentielles sur un projet en cours sur son profil LinkedIn personnel. Vous :", o: ["Commentez publiquement sa publication pour lui signaler l'erreur.", "Contactez immédiatement le collaborateur en privé, signalez la situation au manager ou au RH selon la gravité.", "Signalez la publication à LinkedIn pour qu'elle la supprime.", "Attendez de voir si quelqu'un d'autre réagit avant d'intervenir."], c: 1, e: "Intervention discrète + rapide + escalade selon gravité. A = aggraver · C = délai · D = inertie." },
  { s: "Aptitudes Social Media", t: "Votre responsable vous demande de mesurer l'efficacité d'une campagne de notoriété sur LinkedIn. Quel indicateur est le plus pertinent ?", o: ["Le nombre de clics sur le lien dans les posts.", "Le taux de conversion en nouveaux abonnés payants.", "La portée organique et le taux d'engagement (impressions, likes, commentaires, partages).", "Le coût par acquisition client."], c: 2, e: "Notoriété = portée + engagement. A, B = conversion · D = paid." },
  { s: "Aptitudes Social Media", t: "Un de vos posts reçoit un commentaire négatif d'un concurrent qui critique ouvertement les services IZICHANGE. Vous :", o: ["Répondez de façon agressive pour défendre IZICHANGE.", "Ignorez le commentaire — répondre lui donnera de la visibilité.", "Répondez calmement en donnant des faits concrets sur les services IZICHANGE, sans attaquer le concurrent, et invitez à une discussion directe en privé.", "Supprimez le commentaire."], c: 2, e: "Réponse factuelle + sans attaque = marque mature. A = mauvaise image · B = laisse l'accusation · D = censure visible." },
  { s: "Aptitudes Social Media", t: "Votre manager vous demande de créer du contenu sur un sujet que vous ne maîtrisez pas (nouvelle réglementation fintech). Vous :", o: ["Créez le contenu avec vos connaissances générales sans le signaler.", "Faites des recherches approfondies, soumettez le contenu pour validation à l'équipe Compliance ou AML avant publication.", "Refusez de créer ce contenu — ce n'est pas votre domaine d'expertise.", "Publiez le contenu en ajoutant une mention 'à titre informatif'."], c: 1, e: "Contenu réglementaire fintech = validation experte avant publication. A = désinformation · C = rigidité · D = décharge insuffisante." },
  { s: "Aptitudes Social Media", t: "Votre compte Instagram professionnel est hacké. Des posts non autorisés ont été publiés. Votre première action :", o: ["Supprimez les posts problématiques et changez le mot de passe.", "Alertez immédiatement votre manager et le responsable technique, sécurisez le compte (mot de passe, 2FA, révocation des accès tiers), publiez un message de transparence aux abonnés et documentez l'incident.", "Publiez un story pour prévenir les abonnés que le compte a été hacké.", "Attendez de savoir si quelqu'un a remarqué avant d'agir."], c: 1, e: "Incident de sécurité = escalade + sécurisation + transparence + documentation. A = partiel · C = sans sécurisation · D = inertie dangereuse." },
  { s: "Aptitudes Social Media", t: "Votre manager vous demande de suivre une tendance virale (challenge TikTok) qui ne correspond pas à l'image professionnelle de la marque. Vous :", o: ["Participez sans hésiter — la viralité prime en social media.", "Refusez catégoriquement — IZICHANGE est une fintech sérieuse.", "Présentez à votre manager une analyse rapide : adéquation avec la cible et les valeurs de marque, risques et opportunités, et proposez une version adaptée au positionnement IZICHANGE si pertinent.", "Participez à la tendance mais en version très légère pour minimiser les risques."], c: 2, e: "Strategic fit avant viralité. A = manque de discernement · B = rigidité · D = compromis peu satisfaisant." },
];

/* ─── Bloc 3C — IT commun (partagé cyber + dev) ──────────────────────── */
const IT_COMMON: RawQ[] = [
  { s: "IT — Commun", t: "Votre collègue vous demande de partager vos identifiants pour une action urgente. Vous :", o: ["Partagez — c'est un collègue de confiance et c'est urgent.", "Refusez et proposez des alternatives : accès temporaire via le manager ou l'administrateur système.", "Partagez mais lui demandez de ne pas les mémoriser.", "Créez un nouveau compte temporaire avec vos droits pour lui."], c: 1, e: "Partage d'identifiants = violation de sécurité fondamentale. B = seule réponse conforme. A, C = à risque · D = dépasse les droits." },
  { s: "IT — Commun", t: "Vous identifiez une faille de sécurité mineure qui n'affecte pas les opérations actuelles. Vous :", o: ["Attendez la prochaine réunion technique.", "La corrigez vous-même si vous avez les droits.", "La documentez, la signalez immédiatement au responsable sécurité avec une description précise et suivez le process de gestion des vulnérabilités.", "Gardez l'information — une faille mineure ne justifie pas une alerte."], c: 2, e: "Toute faille doit être documentée et remontée. C = bonne pratique DevSecOps. B = non coordonné · D = négligence · A = délai inacceptable." },
  { s: "IT — Commun", t: "On vous demande d'estimer le délai pour une nouvelle fonctionnalité sans analyse des specs. Vous :", o: ["Donnez une estimation rapide pour montrer votre réactivité.", "Refusez d'estimer avant d'avoir analysé les spécifications.", "Donnez une fourchette large en précisant que vous affinerez après analyse des specs.", "Déléguez l'estimation à un collègue plus expérimenté."], c: 2, e: "Estimation sans analyse = dérapage. C = honnêteté + engagement d'affinage. A = sans base · B = rigidité · D = abdication." },
  { s: "IT — Commun", t: "Bug bloquant découvert en staging à J-1 de la livraison production. Votre première action :", o: ["Déployez quand même et corrigez en post-déploiement.", "Alertez immédiatement manager et équipe, documentez le bug et évaluez si un hotfix est faisable dans les délais.", "Travaillez toute la nuit pour le corriger sans en parler à personne.", "Informez le client du report sans consulter votre équipe."], c: 1, e: "Bug bloquant = alert immédiate + diagnostic + décision collective. A = risque production · C = héroïsme · D = communication prématurée." },
  { s: "IT — Commun", t: "Solution rapide (dette technique) vs propre (2x plus longue) pour une démo client dans 5 jours. Vous :", o: ["Solution rapide — la démo prime.", "Solution propre — la dette technique est toujours coûteuse.", "Solution rapide pour la démo en documentant la dette avec un plan de remédiation daté.", "Demandez au client de reporter la démo."], c: 2, e: "Pragmatisme mature = livrer + tracer la dette + planifier. A = court-termisme · B = idéalisme · D = hors périmètre." },
];

/* ─── Bloc 3C — spécifique Cybersécurité ─────────────────────────────── */
const CYBER_SPEC: RawQ[] = [
  { s: "Cybersécurité", t: "Logs : tentatives de connexion SSH échouées répétées depuis une même IP étrangère. Votre diagnostic :", o: ["Un bug dans le système de logging.", "Un scan automatique réseau sans intention malveillante.", "Une attaque par force brute probable — bloquez l'IP, renforcez la politique SSH et alertez le responsable sécurité.", "Un accès légitime d'un partenaire mal configuré."], c: 2, e: "Tentatives répétées SSH depuis IP externe = signature brute force. C = réponse technique et procédurale correcte." },
  { s: "Cybersécurité", t: "Email de 'support@izichange-secure.com' demandant de confirmer le mot de passe d'un utilisateur. Votre analyse :", o: ["Probablement légitime d'une équipe sécurité interne.", "Email de phishing — domaine différent du domaine officiel, aucune entreprise légitime ne demande un mot de passe par email.", "Vérifier si l'utilisateur a un problème de compte avant de conclure.", "Faux positif des filtres antispam."], c: 1, e: "Deux signaux : domaine suspect (typosquatting) + demande de mot de passe par email (jamais légitime)." },
  { s: "Cybersécurité", t: "On vous demande de réaliser un pentest sur le système d'un partenaire. Votre première étape :", o: ["Commencez immédiatement le scan.", "Exigez un document d'autorisation écrite signé par le partenaire avant toute action.", "Demandez les credentials d'administrateur.", "Demandez quelles vulnérabilités il soupçonne déjà."], c: 1, e: "Pentest sans autorisation écrite = activité illégale. B est non-négociable. A = acte illégal · D = biais le test." },
];

/* ─── Bloc 3C — spécifique Développeur ───────────────────────────────── */
const DEV_SPEC: RawQ[] = [
  { s: "Développeur", t: "SQL ou NoSQL pour stocker les données de transactions financières d'IZICHANGE ?", o: ["NoSQL — plus performant pour les grandes volumétries.", "SQL — les transactions financières nécessitent des garanties ACID que les bases relationnelles offrent nativement.", "Les deux en parallèle — SQL pour l'historique, NoSQL pour le temps réel.", "NoSQL — plus flexible pour les mises à jour fréquentes de structure."], c: 1, e: "Données financières = ACID obligatoire. SQL par défaut. NoSQL sacrifie certaines garanties ACID." },
  { s: "Développeur", t: "Votre code passe tous les tests unitaires mais échoue en intégration. Cause la plus probable :", o: ["Un bug dans le framework de tests unitaires.", "Un problème dans les interactions entre composants — interface, contrat d'API, données partagées ou configuration d'environnement.", "Les tests unitaires ne couvrent pas les bons scénarios.", "Un problème de performance lié au volume de données."], c: 1, e: "Tests unitaires = composants isolés. Échec en intégration = interactions entre composants." },
];

function toSeed(block: number, domain: Domain | null, arr: RawQ[]): SeedQuestion[] {
  return arr.map((q) => ({
    block,
    domain,
    section: q.s,
    text: q.t,
    options: q.o,
    correctIndex: q.c,
    explanation: q.e,
  }));
}

export const SEED_QUESTIONS: SeedQuestion[] = [
  ...toSeed(1, null, B1),
  ...toSeed(2, null, B2),
  ...toSeed(3, "ops", OPS),
  ...toSeed(3, "graphiste", GRAPHISTE),
  ...toSeed(3, "crm", CRM),
  ...toSeed(3, "social", SOCIAL),
  ...toSeed(3, "cyber", [...IT_COMMON, ...CYBER_SPEC]),
  ...toSeed(3, "dev", [...IT_COMMON, ...DEV_SPEC]),
];
